-- Enforce tenant isolation after externally provisioning the roles documented in
-- scripts/postgres/provision-roles.sql. This migration is intentionally atomic:
-- runtime role grants, policies, and FORCE ROW LEVEL SECURITY land together.

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE, CREATE ON SCHEMA public TO feed_radar_owner;
GRANT USAGE ON SCHEMA public TO feed_radar_app, feed_radar_auth, feed_radar_worker, feed_radar_readonly;

CREATE OR REPLACE FUNCTION feed_radar_tenant_id()
RETURNS UUID
LANGUAGE SQL
STABLE
SECURITY INVOKER
SET search_path = pg_catalog
AS $$
    SELECT NULLIF(current_setting('app.user_id', true), '')::UUID
$$;

REVOKE ALL ON FUNCTION feed_radar_tenant_id() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION feed_radar_tenant_id() TO feed_radar_app, feed_radar_readonly;

-- Authentication is the only unauthenticated path to users. These functions
-- execute with the migration owner, pin search_path, and expose only reviewed
-- operations; feed_radar_auth receives no direct table privilege.
CREATE OR REPLACE FUNCTION feed_radar_auth_find_user(requested_email TEXT)
RETURNS TABLE (
    id UUID,
    email VARCHAR(255),
    password_hash VARCHAR(255),
    display_name VARCHAR(100),
    tier VARCHAR(20)
)
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
    SELECT users.id, users.email, users.password_hash, users.display_name, users.tier
    FROM public.users
    WHERE users.email = requested_email AND users.deleted_at IS NULL
$$;

CREATE OR REPLACE FUNCTION feed_radar_auth_register(
    requested_email TEXT,
    requested_password_hash TEXT,
    requested_display_name TEXT
)
RETURNS TABLE (
    id UUID,
    email VARCHAR(255),
    password_hash VARCHAR(255),
    display_name VARCHAR(100),
    tier VARCHAR(20)
)
LANGUAGE SQL
VOLATILE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
    INSERT INTO public.users (email, password_hash, display_name, tier)
    VALUES (requested_email, requested_password_hash, requested_display_name, 'free')
    RETURNING users.id, users.email, users.password_hash, users.display_name, users.tier
$$;

CREATE OR REPLACE FUNCTION feed_radar_auth_touch_last_login(requested_user_id UUID)
RETURNS VOID
LANGUAGE SQL
VOLATILE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
    UPDATE public.users SET last_login_at = NOW() WHERE id = requested_user_id
$$;

REVOKE ALL ON FUNCTION feed_radar_auth_find_user(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION feed_radar_auth_register(TEXT, TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION feed_radar_auth_touch_last_login(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION feed_radar_auth_find_user(TEXT) TO feed_radar_auth;
GRANT EXECUTE ON FUNCTION feed_radar_auth_register(TEXT, TEXT, TEXT) TO feed_radar_auth;
GRANT EXECUTE ON FUNCTION feed_radar_auth_touch_last_login(UUID) TO feed_radar_auth;

REVOKE ALL ON TABLE
    users, folders, feeds, articles, rules, rule_evaluations, tags,
    article_tags, sessions, stripe_customers, subscriptions, usage_records,
    usage_daily, invoices, payment_methods, billing_events, dunning_history,
    feed_categories, webhook_events
FROM PUBLIC;

GRANT SELECT, UPDATE, DELETE ON users TO feed_radar_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON
    folders, feeds, articles, rules, rule_evaluations, tags, article_tags,
    sessions, stripe_customers, subscriptions, usage_records, usage_daily,
    invoices, payment_methods, billing_events, dunning_history, feed_categories
TO feed_radar_app;
GRANT SELECT ON
    users, folders, feeds, articles, rules, rule_evaluations, tags,
    article_tags, sessions, stripe_customers, subscriptions, usage_records,
    usage_daily, invoices, payment_methods, billing_events, dunning_history,
    feed_categories
TO feed_radar_readonly;

-- Worker access is explicit per operation group. It is cross-tenant by design,
-- but never relies on ownership, superuser, or BYPASSRLS.
GRANT SELECT, UPDATE, DELETE ON users TO feed_radar_worker;
GRANT SELECT, UPDATE ON feeds TO feed_radar_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON articles TO feed_radar_worker;
GRANT SELECT, UPDATE ON rules TO feed_radar_worker;
GRANT INSERT ON rule_evaluations TO feed_radar_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON feed_categories TO feed_radar_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON
    stripe_customers, subscriptions, usage_records, usage_daily, invoices,
    payment_methods, billing_events, dunning_history, webhook_events
TO feed_radar_worker;

-- All UUID primary keys are generated by functions today; this also keeps future
-- owner-created sequences inaccessible unless deliberately granted.
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM PUBLIC;

-- Cross-table references must carry the same tenant. Existing single-column
-- foreign keys keep their delete semantics; these composite constraints add the
-- tenant invariant and deliberately fail migration on historical corruption.
ALTER TABLE folders ADD CONSTRAINT folders_id_user_key UNIQUE (id, user_id);
ALTER TABLE feeds ADD CONSTRAINT feeds_id_user_key UNIQUE (id, user_id);
ALTER TABLE rules ADD CONSTRAINT rules_id_user_key UNIQUE (id, user_id);
ALTER TABLE stripe_customers ADD CONSTRAINT stripe_customers_id_user_key UNIQUE (id, user_id);
ALTER TABLE subscriptions ADD CONSTRAINT subscriptions_id_user_key UNIQUE (id, user_id);

ALTER TABLE folders ADD CONSTRAINT folders_parent_tenant_fk
    FOREIGN KEY (parent_id, user_id) REFERENCES folders (id, user_id);
ALTER TABLE feeds ADD CONSTRAINT feeds_folder_tenant_fk
    FOREIGN KEY (folder_id, user_id) REFERENCES folders (id, user_id);
ALTER TABLE articles ADD CONSTRAINT articles_feed_tenant_fk
    FOREIGN KEY (feed_id, user_id) REFERENCES feeds (id, user_id);
ALTER TABLE articles ADD CONSTRAINT articles_hidden_rule_tenant_fk
    FOREIGN KEY (hidden_by_rule_id, user_id) REFERENCES rules (id, user_id);
ALTER TABLE rules ADD CONSTRAINT rules_feed_tenant_fk
    FOREIGN KEY (feed_id, user_id) REFERENCES feeds (id, user_id);
ALTER TABLE rules ADD CONSTRAINT rules_folder_tenant_fk
    FOREIGN KEY (folder_id, user_id) REFERENCES folders (id, user_id);
ALTER TABLE subscriptions ADD CONSTRAINT subscriptions_customer_tenant_fk
    FOREIGN KEY (stripe_customer_id, user_id) REFERENCES stripe_customers (id, user_id);
ALTER TABLE usage_records ADD CONSTRAINT usage_records_subscription_tenant_fk
    FOREIGN KEY (subscription_id, user_id) REFERENCES subscriptions (id, user_id);
ALTER TABLE invoices ADD CONSTRAINT invoices_subscription_tenant_fk
    FOREIGN KEY (subscription_id, user_id) REFERENCES subscriptions (id, user_id);
ALTER TABLE payment_methods ADD CONSTRAINT payment_methods_customer_tenant_fk
    FOREIGN KEY (stripe_customer_id, user_id) REFERENCES stripe_customers (id, user_id);
ALTER TABLE dunning_history ADD CONSTRAINT dunning_subscription_tenant_fk
    FOREIGN KEY (subscription_id, user_id) REFERENCES subscriptions (id, user_id);

-- Direct ownership policies.
CREATE POLICY users_owner ON users TO feed_radar_owner USING (true) WITH CHECK (true);
CREATE POLICY users_tenant ON users TO feed_radar_app, feed_radar_readonly
    USING (id = feed_radar_tenant_id()) WITH CHECK (id = feed_radar_tenant_id());
CREATE POLICY users_worker ON users TO feed_radar_worker USING (true) WITH CHECK (true);

CREATE POLICY folders_owner ON folders TO feed_radar_owner USING (true) WITH CHECK (true);
CREATE POLICY folders_tenant ON folders TO feed_radar_app, feed_radar_readonly
    USING (user_id = feed_radar_tenant_id()) WITH CHECK (user_id = feed_radar_tenant_id());

CREATE POLICY feeds_owner ON feeds TO feed_radar_owner USING (true) WITH CHECK (true);
CREATE POLICY feeds_tenant ON feeds TO feed_radar_app, feed_radar_readonly
    USING (user_id = feed_radar_tenant_id()) WITH CHECK (user_id = feed_radar_tenant_id());
CREATE POLICY feeds_worker ON feeds TO feed_radar_worker USING (true) WITH CHECK (true);

CREATE POLICY articles_owner ON articles TO feed_radar_owner USING (true) WITH CHECK (true);
CREATE POLICY articles_tenant ON articles TO feed_radar_app, feed_radar_readonly
    USING (user_id = feed_radar_tenant_id()) WITH CHECK (user_id = feed_radar_tenant_id());
CREATE POLICY articles_worker ON articles TO feed_radar_worker USING (true) WITH CHECK (true);

CREATE POLICY rules_owner ON rules TO feed_radar_owner USING (true) WITH CHECK (true);
CREATE POLICY rules_tenant ON rules TO feed_radar_app, feed_radar_readonly
    USING (user_id = feed_radar_tenant_id()) WITH CHECK (user_id = feed_radar_tenant_id());
CREATE POLICY rules_worker ON rules TO feed_radar_worker USING (true) WITH CHECK (true);

CREATE POLICY tags_owner ON tags TO feed_radar_owner USING (true) WITH CHECK (true);
CREATE POLICY tags_tenant ON tags TO feed_radar_app, feed_radar_readonly
    USING (user_id = feed_radar_tenant_id()) WITH CHECK (user_id = feed_radar_tenant_id());

CREATE POLICY sessions_owner ON sessions TO feed_radar_owner USING (true) WITH CHECK (true);
CREATE POLICY sessions_tenant ON sessions TO feed_radar_app, feed_radar_readonly
    USING (user_id = feed_radar_tenant_id()) WITH CHECK (user_id = feed_radar_tenant_id());

CREATE POLICY stripe_customers_owner ON stripe_customers TO feed_radar_owner USING (true) WITH CHECK (true);
CREATE POLICY stripe_customers_tenant ON stripe_customers TO feed_radar_app, feed_radar_readonly
    USING (user_id = feed_radar_tenant_id()) WITH CHECK (user_id = feed_radar_tenant_id());
CREATE POLICY stripe_customers_worker ON stripe_customers TO feed_radar_worker USING (true) WITH CHECK (true);

CREATE POLICY subscriptions_owner ON subscriptions TO feed_radar_owner USING (true) WITH CHECK (true);
CREATE POLICY subscriptions_tenant ON subscriptions TO feed_radar_app, feed_radar_readonly
    USING (user_id = feed_radar_tenant_id()) WITH CHECK (user_id = feed_radar_tenant_id());
CREATE POLICY subscriptions_worker ON subscriptions TO feed_radar_worker USING (true) WITH CHECK (true);

CREATE POLICY usage_records_owner ON usage_records TO feed_radar_owner USING (true) WITH CHECK (true);
CREATE POLICY usage_records_tenant ON usage_records TO feed_radar_app, feed_radar_readonly
    USING (user_id = feed_radar_tenant_id()) WITH CHECK (user_id = feed_radar_tenant_id());
CREATE POLICY usage_records_worker ON usage_records TO feed_radar_worker USING (true) WITH CHECK (true);

CREATE POLICY usage_daily_owner ON usage_daily TO feed_radar_owner USING (true) WITH CHECK (true);
CREATE POLICY usage_daily_tenant ON usage_daily TO feed_radar_app, feed_radar_readonly
    USING (user_id = feed_radar_tenant_id()) WITH CHECK (user_id = feed_radar_tenant_id());
CREATE POLICY usage_daily_worker ON usage_daily TO feed_radar_worker USING (true) WITH CHECK (true);

CREATE POLICY invoices_owner ON invoices TO feed_radar_owner USING (true) WITH CHECK (true);
CREATE POLICY invoices_tenant ON invoices TO feed_radar_app, feed_radar_readonly
    USING (user_id = feed_radar_tenant_id()) WITH CHECK (user_id = feed_radar_tenant_id());
CREATE POLICY invoices_worker ON invoices TO feed_radar_worker USING (true) WITH CHECK (true);

CREATE POLICY payment_methods_owner ON payment_methods TO feed_radar_owner USING (true) WITH CHECK (true);
CREATE POLICY payment_methods_tenant ON payment_methods TO feed_radar_app, feed_radar_readonly
    USING (user_id = feed_radar_tenant_id()) WITH CHECK (user_id = feed_radar_tenant_id());
CREATE POLICY payment_methods_worker ON payment_methods TO feed_radar_worker USING (true) WITH CHECK (true);

CREATE POLICY billing_events_owner ON billing_events TO feed_radar_owner USING (true) WITH CHECK (true);
CREATE POLICY billing_events_tenant ON billing_events TO feed_radar_app, feed_radar_readonly
    USING (user_id = feed_radar_tenant_id()) WITH CHECK (user_id = feed_radar_tenant_id());
CREATE POLICY billing_events_worker ON billing_events TO feed_radar_worker USING (true) WITH CHECK (true);

CREATE POLICY dunning_history_owner ON dunning_history TO feed_radar_owner USING (true) WITH CHECK (true);
CREATE POLICY dunning_history_tenant ON dunning_history TO feed_radar_app, feed_radar_readonly
    USING (user_id = feed_radar_tenant_id()) WITH CHECK (user_id = feed_radar_tenant_id());
CREATE POLICY dunning_history_worker ON dunning_history TO feed_radar_worker USING (true) WITH CHECK (true);

-- Derived ownership must follow the declared foreign-key path. WITH CHECK also
-- validates the companion rule/tag reference to reject cross-tenant links.
CREATE POLICY rule_evaluations_owner ON rule_evaluations TO feed_radar_owner USING (true) WITH CHECK (true);
CREATE POLICY rule_evaluations_tenant ON rule_evaluations TO feed_radar_app, feed_radar_readonly
    USING (EXISTS (
        SELECT 1 FROM articles
        WHERE articles.id = rule_evaluations.article_id
          AND articles.user_id = feed_radar_tenant_id()
    ))
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM articles
            WHERE articles.id = rule_evaluations.article_id
              AND articles.user_id = feed_radar_tenant_id()
        )
        AND EXISTS (
            SELECT 1 FROM rules
            WHERE rules.id = rule_evaluations.rule_id
              AND rules.user_id = feed_radar_tenant_id()
        )
    );
CREATE POLICY rule_evaluations_worker ON rule_evaluations TO feed_radar_worker USING (true) WITH CHECK (true);

CREATE POLICY article_tags_owner ON article_tags TO feed_radar_owner USING (true) WITH CHECK (true);
CREATE POLICY article_tags_tenant ON article_tags TO feed_radar_app, feed_radar_readonly
    USING (EXISTS (
        SELECT 1 FROM articles
        WHERE articles.id = article_tags.article_id
          AND articles.user_id = feed_radar_tenant_id()
    ))
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM articles
            WHERE articles.id = article_tags.article_id
              AND articles.user_id = feed_radar_tenant_id()
        )
        AND EXISTS (
            SELECT 1 FROM tags
            WHERE tags.id = article_tags.tag_id
              AND tags.user_id = feed_radar_tenant_id()
        )
        AND (
            article_tags.rule_id IS NULL
            OR EXISTS (
                SELECT 1 FROM rules
                WHERE rules.id = article_tags.rule_id
                  AND rules.user_id = feed_radar_tenant_id()
            )
        )
    );

CREATE POLICY feed_categories_owner ON feed_categories TO feed_radar_owner USING (true) WITH CHECK (true);
CREATE POLICY feed_categories_tenant ON feed_categories TO feed_radar_app, feed_radar_readonly
    USING (EXISTS (
        SELECT 1 FROM feeds
        WHERE feeds.id = feed_categories.feed_id
          AND feeds.user_id = feed_radar_tenant_id()
    ))
    WITH CHECK (EXISTS (
        SELECT 1 FROM feeds
        WHERE feeds.id = feed_categories.feed_id
          AND feeds.user_id = feed_radar_tenant_id()
    ));
CREATE POLICY feed_categories_worker ON feed_categories TO feed_radar_worker USING (true) WITH CHECK (true);

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE users FORCE ROW LEVEL SECURITY;
ALTER TABLE folders ENABLE ROW LEVEL SECURITY;
ALTER TABLE folders FORCE ROW LEVEL SECURITY;
ALTER TABLE feeds ENABLE ROW LEVEL SECURITY;
ALTER TABLE feeds FORCE ROW LEVEL SECURITY;
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE articles FORCE ROW LEVEL SECURITY;
ALTER TABLE rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE rules FORCE ROW LEVEL SECURITY;
ALTER TABLE rule_evaluations ENABLE ROW LEVEL SECURITY;
ALTER TABLE rule_evaluations FORCE ROW LEVEL SECURITY;
ALTER TABLE tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE tags FORCE ROW LEVEL SECURITY;
ALTER TABLE article_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE article_tags FORCE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions FORCE ROW LEVEL SECURITY;
ALTER TABLE stripe_customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE stripe_customers FORCE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions FORCE ROW LEVEL SECURITY;
ALTER TABLE usage_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE usage_records FORCE ROW LEVEL SECURITY;
ALTER TABLE usage_daily ENABLE ROW LEVEL SECURITY;
ALTER TABLE usage_daily FORCE ROW LEVEL SECURITY;
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices FORCE ROW LEVEL SECURITY;
ALTER TABLE payment_methods ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_methods FORCE ROW LEVEL SECURITY;
ALTER TABLE billing_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE billing_events FORCE ROW LEVEL SECURITY;
ALTER TABLE dunning_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE dunning_history FORCE ROW LEVEL SECURITY;
ALTER TABLE feed_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE feed_categories FORCE ROW LEVEL SECURITY;
