-- Provision Feed Radar group roles before running product migrations.
-- Login principals and credentials are platform concerns: grant exactly one of
-- these NOLOGIN roles to each dedicated principal and connect with SET ROLE.

SELECT 'CREATE ROLE feed_radar_owner NOLOGIN NOINHERIT NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE'
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'feed_radar_owner')\gexec
SELECT 'CREATE ROLE feed_radar_app NOLOGIN NOINHERIT NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE'
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'feed_radar_app')\gexec
SELECT 'CREATE ROLE feed_radar_auth NOLOGIN NOINHERIT NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE'
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'feed_radar_auth')\gexec
SELECT 'CREATE ROLE feed_radar_worker NOLOGIN NOINHERIT NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE'
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'feed_radar_worker')\gexec
SELECT 'CREATE ROLE feed_radar_readonly NOLOGIN NOINHERIT NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE'
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'feed_radar_readonly')\gexec

ALTER ROLE feed_radar_owner NOLOGIN NOINHERIT NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
ALTER ROLE feed_radar_app NOLOGIN NOINHERIT NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
ALTER ROLE feed_radar_auth NOLOGIN NOINHERIT NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
ALTER ROLE feed_radar_worker NOLOGIN NOINHERIT NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
ALTER ROLE feed_radar_readonly NOLOGIN NOINHERIT NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;

SELECT format(
    'GRANT CONNECT ON DATABASE %I TO feed_radar_owner, feed_radar_app, feed_radar_auth, feed_radar_worker, feed_radar_readonly',
    current_database()
)\gexec
GRANT USAGE, CREATE ON SCHEMA public TO feed_radar_owner;
